/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformResult {
  code: string
  transformed: boolean
  /** JSON-serialized v3 source map, if source maps are enabled. */
  sourceMap?: string
}
export interface TransformOptions {
  compilationMode?: string
  outputMode?: string
  /** Enable source map generation. */
  sourceMap?: boolean
  /** Import source for gating function (e.g., "my-flags"). */
  gatingImportSource?: string
  /** Function name for gating check (e.g., "isCompilerEnabled"). */
  gatingFunctionName?: string
}
export declare function transformReactFile(source: string, filename: string, options?: TransformOptions | undefined | null): TransformResult
export interface TransformTimedResult {
  code: string
  transformed: boolean
  sourceMap?: string
  /** Rust-side compilation time in nanoseconds (excludes NAPI marshalling). */
  rustCompileNs: number
}
export declare function transformReactFileTimed(source: string, filename: string, options?: TransformOptions | undefined | null): TransformTimedResult
export interface LintResult {
  diagnostics: Array<LintDiagnostic>
}
export interface LintDiagnostic {
  message: string
  start: number
  end: number
}
export declare function lintReactFile(source: string, filename: string): LintResult
