pub mod aliasing_effects;
pub mod analyse_functions;
pub mod collect_hoistable_property_loads;
pub mod collect_optional_chain_dependencies;
pub mod infer_mutation_aliasing_effects;
pub mod infer_mutation_aliasing_ranges;
pub mod infer_reactive_places;
pub mod infer_types;
pub mod rewrite_instruction_kinds;
